guest_list=['daniel radcliffe', 'emma watson', 'alison brie']
print('The following emails will be sent:')
print(f"Hi {guest_list[0].title()} you're invited!!\n 21/04/2025\t\t at Nagarabhavi.\nPlease be at the venue by 5pm")
print(f"Hi {guest_list[1].title()} you're invited!!\n 21/04/2025\t\t at Nagarabhavi.\nPlease be at the venue by 5pm")
print(f"Hi {guest_list[2].title()} you're invited!!\n 21/04/2025\t\t at Nagarabhavi.\nPlease be at the venue by 5pm")

print()
print('**************************************************')
print('We have found a bigger venue and can accomodate 3 more people\n New set of invites will be sent soon')
print('**************************************************')
print()
print()
guest_list.insert(0, 'peter')
guest_list.insert(2, 'griffin')
guest_list.append('louis')
print(f"Hi {guest_list[0].title()} you're invited!!\n 21/04/2025\t\t at Nagarabhavi.\nPlease be at the venue by 5pm")
print(f"Hi {guest_list[1].title()} you're invited!!\n 21/04/2025\t\t at Nagarabhavi.\nPlease be at the venue by 5pm")
print(f"Hi {guest_list[2].title()} you're invited!!\n 21/04/2025\t\t at Nagarabhavi.\nPlease be at the venue by 5pm")
print(f"Hi {guest_list[3].title()} you're invited!!\n 21/04/2025\t\t at Nagarabhavi.\nPlease be at the venue by 5pm")
print(f"Hi {guest_list[4].title()} you're invited!!\n 21/04/2025\t\t at Nagarabhavi.\nPlease be at the venue by 5pm")
print(f"Hi {guest_list[5].title()} you're invited!!\n 21/04/2025\t\t at Nagarabhavi.\nPlease be at the venue by 5pm")
